// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-team.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-team.ts
var get_my_team_default = defineTool({
  name: "get_my_team",
  title: "Get my FPL team",
  description: "Get the signed-in user's saved Fantasy Premier League team: squad player IDs, captain, bank, free transfers, rank and points.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_teams").select("*").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No team saved yet. Import your FPL team in the app first." }]
      };
    }
    const { data: players } = await supabase.from("players").select("fpl_id, web_name, position, price, form, total_points, status").in("fpl_id", data.player_ids ?? []);
    return {
      content: [{ type: "text", text: JSON.stringify({ team: data, players: players ?? [] }, null, 2) }],
      structuredContent: { team: data, players: players ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-top-predictions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_top_predictions_default = defineTool2({
  name: "get_top_predictions",
  title: "Get top predicted players",
  description: "Get this app's highest predicted point scorers for a gameweek, with price, form and ownership. Omit gameweek_id to use the current gameweek.",
  inputSchema: {
    gameweek_id: z.number().int().optional().describe("Gameweek number. Defaults to the current gameweek."),
    position: z.enum(["GKP", "DEF", "MID", "FWD"]).optional().describe("Filter by position."),
    limit: z.number().int().optional().describe("How many players to return (default 15, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ gameweek_id, position, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let gw = gameweek_id;
    if (!gw) {
      const { data: current } = await supabase.from("gameweeks").select("id").eq("is_current", true).maybeSingle();
      gw = current?.id ?? void 0;
    }
    if (!gw) {
      return { content: [{ type: "text", text: "No current gameweek found." }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 15, 1), 50);
    const { data, error } = await supabase.from("player_predictions").select(
      "predicted_points, player:player_id (fpl_id, web_name, position, price, form, status, selected_by_percent, total_points, teams:team_id (short_name))"
    ).eq("gameweek_id", gw).order("predicted_points", { ascending: false }).limit(120);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter((r) => position ? r.player?.position === position : true).slice(0, take).map((r) => ({
      name: r.player?.web_name,
      team: r.player?.teams?.short_name,
      position: r.player?.position,
      price: r.player?.price,
      form: r.player?.form,
      ownership: r.player?.selected_by_percent,
      status: r.player?.status,
      predicted_points: r.predicted_points
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ gameweek_id: gw, players: rows }, null, 2) }],
      structuredContent: { gameweek_id: gw, players: rows }
    };
  }
});

// src/lib/mcp/tools/search-players.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var search_players_default = defineTool3({
  name: "search_players",
  title: "Search players",
  description: "Search current Premier League players by name and return their FPL stats: price, form, points, ownership and availability status.",
  inputSchema: {
    query: z2.string().describe("Part of a player's name, e.g. 'Salah'."),
    limit: z2.number().int().optional().describe("How many players to return (default 10, max 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const term = query.trim();
    if (!term) {
      return { content: [{ type: "text", text: "query must not be empty" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("players").select(
      "fpl_id, web_name, first_name, second_name, position, price, form, status, minutes, total_points, goals_scored, assists, selected_by_percent, teams:team_id (short_name, name)"
    ).or(`web_name.ilike.%${term}%,second_name.ilike.%${term}%,first_name.ilike.%${term}%`).order("total_points", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 25));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { players: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-gameweek-fixtures.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_gameweek_fixtures_default = defineTool4({
  name: "get_gameweek_fixtures",
  title: "Get gameweek fixtures",
  description: "Get fixtures and difficulty ratings for a gameweek. Omit gameweek_id to use the current gameweek.",
  inputSchema: {
    gameweek_id: z3.number().int().optional().describe("Gameweek number. Defaults to the current gameweek.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ gameweek_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: gwRow } = gameweek_id ? await supabase.from("gameweeks").select("*").eq("id", gameweek_id).maybeSingle() : await supabase.from("gameweeks").select("*").eq("is_current", true).maybeSingle();
    if (!gwRow) {
      return { content: [{ type: "text", text: "Gameweek not found." }], isError: true };
    }
    const { data, error } = await supabase.from("fixtures").select(
      "kickoff_time, finished, home_team_difficulty, away_team_difficulty, home_team:home_team_id (short_name), away_team:away_team_id (short_name)"
    ).eq("gameweek_id", gwRow.id).order("kickoff_time", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { gameweek: gwRow, fixtures: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wxafugdkvvcymluycngf";
var mcp_default = defineMcp({
  name: "fpl-predictor-pro",
  title: "FPL Predictor Pro",
  version: "0.1.0",
  instructions: "Tools for FPL Predictor Pro, a Fantasy Premier League analytics app. Use `get_my_team` for the signed-in manager's squad, `get_top_predictions` for the app's predicted point scorers, `search_players` for player stats, and `get_gameweek_fixtures` for fixtures and difficulty ratings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_team_default, get_top_predictions_default, search_players_default, get_gameweek_fixtures_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
